name: Tamer
version: ${project.version}
authors: [Kokumaji]
main: me.kokumaji.Tamer.Tamer
api-version: 1.13
commands:
  Tamer:
    usage: /Tamer
    aliases: [st, tamer]
    permission: Tamer.command
